var ROOT_PATH = '';
requirejs.config({
	baseUrl:ROOT_PATH+"/dashboard/",
	paths:{
		jquery:"gallary/jquery/jquery-1.11.3.min",
		domReady:"gallary/require/domReady",
		text:"gallary/require/text",
		module:"../module",
		template:"gallary/template/template",
		cookie:"gallary/jquery.cookie/jquery.cookie",
		bootstrap:"gallary/bootstrap/bootstrap.min",
		Api:"const/Api",
		Util:'const/Util',
		jqtree:'gallary/jqtree/tree.jquery'
	},
	shim:{
		cookie:['jquery'],
		jqtree:['jquery'],
		bootstrap:['jquery']
	}
});